[project]
name = "nsw-topo-split"
version = "0.1"
dependencies = [
    "pypdf",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["nsw_topo_split"]
