name: Continuous deployment

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Build release distributions
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          python -m build
      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/project/nsw-topo-split/${{ github.event.release.name }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/
      - name: Publish release distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@b223cbbc63a3e911c7e6093d72760c29bef664f4
        with:
          repository-url: https://test.pypi.org/legacy/
      - name: Test install from TestPyPI
        run: |
          python -m pip install --upgrade pip
          python -m pip install --index-url https://test.pypi.org/simple/ --no-deps nsw-topo-split
      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@b223cbbc63a3e911c7e6093d72760c29bef664f4
